name: finatra integrations document
baseurl: /finatra-integrations
description: A document for integrating grafter, docker-it-scala, and common practice with finatra 2.11
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1-SNAPSHOT
org: docs
markdown: kramdown
