name: finatra integrations
baseurl: /finatra-integrations
description: A guideline for integration and common practice in finatra 2.11
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1-SNAPSHOT
org: docs
markdown: kramdown
