name: finatra common practice
baseurl: /finatra-common-practice
description: Guideline for common practice in finatra 2.11
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1-SNAPSHOT
org: docs
markdown: kramdown
